import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 40,
    backgroundColor: '#FFF6A8',
  },
  logo: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginBottom: 20,
  },
  labellogo: {
    fontSize: 48,
    color: '#229500',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  welcome: {
    fontSize: 18,
    color: '#229500',
    textAlign: 'center',
    marginBottom: 20,
  },
  label: {
    marginBottom: 8,
    fontSize: 18,
    color: '#229500',
    fontWeight: '600',
  },
  input: {
    height: 48,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#229500',
    marginBottom: 16,
    paddingHorizontal: 12,
    fontSize: 16,
    borderRadius: 10,
    color: '#333',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  error: {
    color: 'red',
    marginTop: 12,
    fontSize: 16,
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#229500',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  //Principal
  containerPrincipal: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  titulo: {
    padding: 20,
    backgroundColor: '#229500',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  tituloTx: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#FFF6A8',
  },
  subtituloTx: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
  },
  infoArqui: {
    flex: 1,
    paddingBottom: 20,
    backgroundColor: '#F0F0F0',
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
    margin: 20,
  },
  infoText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 5,
  },
  buttonPrincipal: {
    backgroundColor: '#229500',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  buttonTextPrincipal: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  arquitectoImagen: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
    borderRadius: 10,
    marginBottom: 16,
  },
  //ProyectosObras
  containerProyectosObras: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  tituloProyectos: {
    padding: 20,
    backgroundColor: '#229500',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
},
  tituloTxProyectos: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#FFF6A8',
  },
  containerLista: {
    flex: 1,
    padding: 20,
    backgroundColor: '#FFFFFF',
  },
  itemContainer: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
  },
  nombre: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 8,
  },
  descripcion: {
    fontSize: 16,
    color: '#555555',
    marginBottom: 8,
  },
  botonR: {
    backgroundColor: '#229500',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginTop: 15,
    alignItems: 'center',
  },
  textoBoton: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  cargandoContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cargandoTexto: {
    marginTop: 10,
    fontSize: 18,
    color: '#555555',
  },
  //EscanearQR
  containerQR: {
    flex: 1,
    backgroundColor: '#000',
  },
  scannerContainer: {
    flex: 1,
  },
  scannerCamera: {
    flex: 1,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)', 
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanText: {
    fontSize: 22,
    color: '#FFF',
    fontWeight: '600',
    textAlign: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
    padding: 10,
    borderRadius: 10,
    marginTop: 10,
  },
  rectangleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  rectangle: {
    height: 300,
    width: 300,
    borderWidth: 2,
    borderColor: '#FFF',
    borderRadius: 10, 
    backgroundColor: 'transparent',
    marginBottom: 10, 
  },
  //DetalleOP
  containerDetallePO: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  tituloDetalle: {
    padding: 20,
    backgroundColor: '#229500',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  tituloTxDetalle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF6A8', 
  },
  infoContainerDPO: {
    flex: 1,
    marginTop: 20,
  },
  infoArquiDetalle: {
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    margin: 20,
  },
  detalleTitulo: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#229500', 
    textAlign: 'center',
  },
  detalleTexto: {
    fontSize: 18,
    marginBottom: 5,
    color: 'black',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  botonCerrar: {
    backgroundColor: '#FF6347', 
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 5,
  },
  botonEscaneoQR: {
    backgroundColor: '#229500',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 5,
  },
  textoBotonDetalle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  //GestionarBitacora
  containerGB: {
    flex: 1,
    backgroundColor: "#FFF",
  },
  titulogb: {
    padding: 20,
    backgroundColor: '#229500', 
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  tituloTxgb: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF6A8', 
  },
  infoContainerGB: {
    flex: 1,
  },
  infoArquigb: {
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    margin: 20
  },
  detalleTituloGB: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#229500",
    textAlign: "center",
  },
  detalleTextoGB: {
    fontSize: 18,
    marginBottom: 5,
    color: "black",
  },
  buttonContainerGB: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  buttonGB: {
    backgroundColor: "#229500",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 5,
  },
  buttonTextGB: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  //Agregar Bitacora
  containerAG: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  tituloab: {
    padding: 20,
    backgroundColor: '#229500',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    marginBottom: 10,
  },
  tituloTxAG: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF6A8',
    textAlign: 'center',
  },
  infoArquiSmall: {
    margin: 20,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
        width: 0,
        height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    padding: 10,
  },
  detalleTituloAG: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#000',
  },
  detalleTextoAG: {
    fontSize: 16,
    marginBottom: 10,
    color: '#000',
  },
  inputContainerAG: {
    margin: 20,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
        width: 0,
        height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    padding: 10,
  },
  inputAG: {
    height: 40,
    borderWidth: 1,
    borderColor: '#229500',
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
    color: 'black',
    backgroundColor: '#fff',
  },
  buttonAG: {
    backgroundColor: "#229500",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    margin: 10,
  },
  buttonTextAG: {
    color: '#FFF',
    fontSize: 16,
  },
  imageContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    margin: 10,
  },
  imageWrapper: {
    marginRight: 10,
    marginBottom: 10,
    position: 'relative',
  },
  imageAG: {
    width: 100,
    height: 100,
    borderRadius: 5,
  },
  deleteButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  signatureContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  signatureImage: {
    width: 200,
    height: 100,
    marginBottom: 10,
    borderRadius: 5,
  },
  signatureModal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF6A8',
  },
  signaturePadContainer: {
    width: '95%',
    aspectRatio: 1,
    backgroundColor: '#FFF',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
        width: 0,
        height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    overflow: 'hidden',
  },
  signatureButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    width: '80%',
  },
  scrollContainer: {
    paddingBottom: 15,
  },
  labelAG: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: 'black',
  },
  //Consultar Bitacora
  containerCB: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  titulocb: {
    padding: 20,
    backgroundColor: '#229500',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    marginBottom: 10,
  },
  tituloTxcb: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF6A8',
    textAlign: 'center',
  },
  subtituloTxcb: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#229500',
    textAlign: 'center',
  },
  infoArquicb: {
    margin: 20,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    padding: 20,
  },
  detalleTituloCB: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
    color: "#229500",
  },
  detalleTextocb: {
    fontSize: 16,
    marginBottom: 10,
    color: "#229500",
  },
  modalContainerCB: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalImageContainerCB: {
    width: "90%",
    height: "70%",
    backgroundColor: "#fff",
    borderRadius: 10,
    overflow: "hidden",
  },
  closeButtonCB: {
    position: "absolute",
    top: 20,
    right: 20,
    padding: 10,
    backgroundColor: "#229500",
    borderRadius: 20,
    zIndex: 1,
  },
  closeButtonTextCB: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  bitacoraItem: {
    backgroundColor: '#f0f0f0',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 10,
  },
  infoContainerCB: {
    flex: 1,
    padding: 10,
  },
  modalContentCB: {
    width: '90%',
    height: "70%",
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  linea: {
    borderBottomWidth: 1,
    borderBottomColor: '#229500',
    marginVertical: 8,
    marginLeft: 20,
    marginRight: 20,
  },
});